description = "Convert markdown to PDF using Marp CLI"
prompt = """
Convert markdown files to PDF using Marp CLI.

## Context
- Input file: {{args}}
- Guidelines: @.claude/templates/slide-guidelines.md
- Template: @.claude/templates/slide-design-template.md

## Task

1. Read the input markdown file
2. Read the slide guidelines
3. Simplify the markdown content according to the guidelines
4. Read the design template
5. Apply the template to the simplified content
6. Save to a temporary file
7. Convert to PDF using Marp CLI
8. Clean up the temporary file

Execute the conversion process step by step.
"""
